apiVersion: apps/v1
kind: Deployment
metadata:
 name: mixs-streamlit-front
 labels:
   app: mixs-streamlit
spec:
 selector:
   matchLabels:
     app: mixs-streamlit
     tier: web
 template:
   metadata:
     labels:
       app: mixs-streamlit
       tier: web
   spec:
     containers:
     - name: mixs-streamlit-backend
       image: gcr.io/mixs-298100/app
       ports:
       - containerPort: 8501
